### ISSUE TITLE
February edition of the newsletter?

### ISSUE THREAD

**Issue by prochafilho** [nodeschool/newsletter#5]
When is the next edition of the newsletter coming up?

**Comment by maxogden** [comment]
@prochafilho theres a planning thread here: https://github.com/nodeschool/newsletter/issues/4

I have been pretty busy lately and haven't had time to put it together. If someone else wants to take a stab at drafting it, be my guest! I can help finalize + send it out. Otherwise I expect to get to it in the next month

**Comment by iancrowther** [comment]
Can I request we add some info about the international ns day

https://github.com/nodeschool/international-day/issues/2

**Comment by maxogden** [comment]
sent!

**Comment by iancrowther** [comment]
got it, lgtm
